apiVersion: v1
kind: ResourceQuota
metadata:
  name:
  namespace:

spec:
  hard:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 4
      memory:  8Gi
    pods: 5 #Number of pods can be create inside a NameSpace
    configMap:
    persistentVolumeClaim:
    secrets:
    services: