apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain # Default is delete
volumeBindingMode: WaitForFirstConsumer # Default is immediate
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_RLS # or Standard_LRS
  kind: managed # Default is shared
