kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: name-of-the-RB
  namespace: <namespaceName>

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: name-of-the-role

subjects:
- kind: Group
  namespace: <namespaceName>
  name: "AzureADID"